title: Ephemera
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum", "sunrise"
description: Transitory thoughts about stuff I care about
name: Christopher Allen
include:
  - _pages
  - _posts
plugins:
  - jekyll-include-cache
atom_feed:
  hide: true
